name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇪🇪_1"
    type: vless
    server: "94.183.170.135"
    port: 8443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy4.lockdwn.com"
    client-fingerprint: "firefox"
  - name: "🇪🇪_2"
    type: vless
    server: "95.85.228.161"
    port: 8443
    uuid: "7e8f7489-e65f-4be6-93ed-867a74ec6759"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇪🇪_3"
    type: vless
    server: "31.76.70.31"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "baltic.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "t_qv0VOfWhKZJV_giGC55-ipgHYWo44Yfvik_B8T8ik"
      short-id: "4a46213c935e2ee4"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_4"
    type: vless
    server: "31.76.70.32"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "baltic.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "t_qv0VOfWhKZJV_giGC55-ipgHYWo44Yfvik_B8T8ik"
      short-id: "4a46213c935e2ee4"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_5"
    type: vless
    server: "95.85.224.3"
    port: 8443
    uuid: "7e8f7489-e65f-4be6-93ed-867a74ec6759"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇪🇪_6"
    type: vless
    server: "94.183.170.231"
    port: 8443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy2.lockdwn.com"
    client-fingerprint: "firefox"
  - name: "🇪🇪_7"
    type: vless
    server: "31.56.187.86"
    port: 443
    uuid: "a261baf0-8e37-4ff0-b9d1-7180c570073a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ee.dealfre.xyz"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Zo3OftHANSWinV-kajh98gqzcjWnkB_q7JPaG87SMGA"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇪🇪_8"
    type: trojan
    server: "109.206.241.10"
    port: 449
    password: "oiiaB38ywjEHCWRs_O_a_1113_Il_KeyyyHop_Bes1"
    sni: "russiapower.accesscam.org"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"

rules:
  - MATCH,PROXY
