name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇫🇮_1"
    type: vless
    server: "87.121.89.80"
    port: 13443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_2"
    type: vless
    server: "fi1.levikogjgfdd.ir"
    port: 443
    uuid: "fbb74aa8-b89a-4f20-9504-6b25aadf6681"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fin2.freeinternat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_3"
    type: vless
    server: "185.79.138.71"
    port: 448
    uuid: "0b0915d7-6800-4580-a44b-77d84f105e6a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "CsDgNRcCwCkPIslfZpKTIK71KFpIFNsotbdzKcZVoH8"
      short-id: "cd21e552537c7c0b"
  - name: "🇫🇮_4"
    type: vless
    server: "83.219.97.128"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nordic.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "YQTixaXzPVImuRc4TUbrFAekjIiaYV-t5S-HTKlH0AU"
      short-id: "2186a755ed67b034"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_5"
    type: vless
    server: "132.243.223.88"
    port: 443
    uuid: "fbb74aa8-b89a-4f20-9504-6b25aadf6681"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fin2.freeinternat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_6"
    type: vless
    server: "2.26.100.192"
    port: 445
    uuid: "40205ae5-d30f-4216-b2e0-0506dbbd382e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Ku60WZ3HEdE07DoEBJ5I9o_fjcN_bhdK8bTW3RJjBmM"
      short-id: "c226283c4de5b1ad"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_7"
    type: vless
    server: "157.180.119.87"
    port: 2087
    uuid: "d01d5a74-09fb-4e9e-b0d9-38b5fd77ad70"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "92SyLtOmKXvLc6wSMew9sRpmRfVY_BwywV8Mf5r-p2s"
      short-id: "72ce50a0"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇫🇮_8"
    type: vless
    server: "5.61.91.221"
    port: 443
    uuid: "03446511-2806-0021-b02f-f10d2d3a33c6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn-up.perecbass.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "4a7b1c8d"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_9"
    type: vless
    server: "87.121.89.80"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nordic.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "YQTixaXzPVImuRc4TUbrFAekjIiaYV-t5S-HTKlH0AU"
      short-id: "2186a755ed67b034"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_10"
    type: vless
    server: "150.241.86.150"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nordic.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "YQTixaXzPVImuRc4TUbrFAekjIiaYV-t5S-HTKlH0AU"
      short-id: "2186a755ed67b034"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_11"
    type: vless
    server: "ru.lobbytech.ru"
    port: 2087
    uuid: "d01d5a74-09fb-4e9e-b0d9-38b5fd77ad70"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "iWxxH0TWB1Ciz6sEwtfjUVY61OcTDihou5IJfkt0O0Q"
      short-id: "f2a4c6e8"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇫🇮_12"
    type: vless
    server: "31.76.46.138"
    port: 20422
    uuid: "d8523317-503e-43ad-b2c3-e5f77d725848"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "ZUQTvwYk_hDqSrw36uc18MkeEIXIGZZGsf5XWVwdqAQ"
      short-id: "90"
  - name: "🇫🇮_13"
    type: vless
    server: "5.61.91.206"
    port: 443
    uuid: "d427a02f-e0ea-0021-9cfb-66c1866ca3ce"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn-up.perecbass.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "6a2b5c9d"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_14"
    type: vless
    server: "5.61.91.206"
    port: 443
    uuid: "bd99da97-265e-0021-82cc-4ec009fe9ce2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "0a4b7c3d"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_15"
    type: vless
    server: "77.91.84.96"
    port: 57228
    uuid: "f319a005-6bd0-44b3-910c-a596a2573efe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.googletagmanager.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "iWiQ0JyYhl_yzWSbIh4L4wOiiXBOhNVMhWmgtDvF1jo"
      short-id: "6e3e0d3abe3e78a4"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_16"
    type: vless
    server: "72.35.246.31"
    port: 1244
    uuid: "2d96d4d6-a276-4ab5-9f20-8dc5cbf6e902"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "axisvpn.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "gHG_cbbi-OJKY2tBQTqz1QryfmmRZEQ7BQgymimukkQ"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_17"
    type: vless
    server: "83.219.97.128"
    port: 13443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_18"
    type: vless
    server: "5.181.21.234"
    port: 443
    uuid: "d7fc372d-c057-43ce-8070-9b96abbc60f3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fl4.raketa-balance.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "JaP4bhvIMW-l7T0_RkLra59DeBYI6W9XemKa8MyRPSY"
      short-id: "6c6082a2223c1d03"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_19"
    type: vless
    server: "132.243.223.84"
    port: 443
    uuid: "fbb74aa8-b89a-4f20-9504-6b25aadf6681"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fin2.freeinternat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_20"
    type: vless
    server: "77.110.108.231"
    port: 8898
    uuid: "b91abe1a-80ca-417b-998b-2b542661c16f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "play.googleapis.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "y2ciDMmaLyu1U7wEG7Wi9buO91wWHnRtWfPLGjSZHC8"
      short-id: "6633e065744286"
  - name: "🇫🇮_21"
    type: vless
    server: "2.26.100.192"
    port: 2087
    uuid: "40205ae5-d30f-4216-b2e0-0506dbbd382e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Ku60WZ3HEdE07DoEBJ5I9o_fjcN_bhdK8bTW3RJjBmM"
      short-id: "c226283c4de5b1ad"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇫🇮_22"
    type: vless
    server: "fin2.freeinternat.com"
    port: 443
    uuid: "fbb74aa8-b89a-4f20-9504-6b25aadf6681"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fin2.freeinternat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_23"
    type: vless
    server: "200.165.230.19"
    port: 443
    uuid: "d01d5a74-09fb-4e9e-b0d9-38b5fd77ad70"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.kinopoisk.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "iWxxH0TWB1Ciz6sEwtfjUVY61OcTDihou5IJfkt0O0Q"
      short-id: "a3f8d21c4b907e56"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_24"
    type: trojan
    server: "65.108.205.61"
    port: 443
    password: "88939272-790a-441f-b12b-8ce531aca810"
    sni: "polo01.kctr2038.icu"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_25"
    type: trojan
    server: "65.108.205.61"
    port: 443
    password: "62b78c9b-16cb-4ee6-824b-a4f856cf18f3"
    sni: "65.108.205.61"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_26"
    type: trojan
    server: "144.31.82.35"
    port: 443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_27"
    type: ss
    server: "31.76.30.79"
    port: 10808
    cipher: "chacha20-ietf-poly1305"
    password: "TmXSpcRBbhvHDg66bo2w89bToxQsbMoa"
    udp: true
  - name: "🇫🇮_28"
    type: ss
    server: "31.76.30.79"
    port: 10808
    cipher: "chacha20-ietf-poly1305"
    password: "TmXSpcRBbhvHDg66bo2w89bToxQsbMoa"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"
      - "🇫🇮_27"
      - "🇫🇮_28"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"
      - "🇫🇮_27"
      - "🇫🇮_28"

rules:
  - MATCH,PROXY
