name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇱🇻_1"
    type: vless
    server: "195.123.210.168"
    port: 13443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_2"
    type: vless
    server: "195.123.208.92"
    port: 13443
    uuid: "fc1b3bda-b226-452a-8c5c-b0e36a1f8f88"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_3"
    type: vless
    server: "89.36.161.222"
    port: 2053
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "cGVu5j95KoeHBkWXveyTKolORbdvZm9g1T6yyo64ZBg"
      short-id: "d26f4703cdd30f4e"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_4"
    type: vless
    server: "195.123.210.168"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-west.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "m6RDw1b8R4lCaRUIzhHpy6TtX2Dhk6nyby8dWzeQqA0"
      short-id: "dd3ff38418d29d22"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_5"
    type: vless
    server: "laoye.in-gect.fun"
    port: 2083
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "laoye.in-gect.fun"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇱🇻_6"
    type: vless
    server: "89.36.161.222"
    port: 2083
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "laoye.in-gect.fun"
    client-fingerprint: "ios"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇱🇻_7"
    type: vless
    server: "31.76.62.167"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-west.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "m6RDw1b8R4lCaRUIzhHpy6TtX2Dhk6nyby8dWzeQqA0"
      short-id: "dd3ff38418d29d22"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_8"
    type: trojan
    server: "tr-latvia1.unlimited-access.ru"
    port: 443
    password: "kxHw-Dk-e9dffgzYszMlEqLJ92AnY3Pi"
    sni: "tr-latvia1.unlimited-access.ru"
    skip-cert-verify: true
    udp: true
  - name: "🇱🇻_9"
    type: trojan
    server: "31.57.61.76"
    port: 2053
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇱🇻_1"
      - "🇱🇻_2"
      - "🇱🇻_3"
      - "🇱🇻_4"
      - "🇱🇻_5"
      - "🇱🇻_6"
      - "🇱🇻_7"
      - "🇱🇻_8"
      - "🇱🇻_9"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇱🇻_1"
      - "🇱🇻_2"
      - "🇱🇻_3"
      - "🇱🇻_4"
      - "🇱🇻_5"
      - "🇱🇻_6"
      - "🇱🇻_7"
      - "🇱🇻_8"
      - "🇱🇻_9"

rules:
  - MATCH,PROXY
