name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇪_1"
    type: vless
    server: "150.241.79.143"
    port: 8443
    uuid: "b9b1e7c9-4160-49b4-85a4-2f096706509a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.oracle.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "dNfk0sOCzOlmE61B7ur7YzU2i08RqXIBcGVBA2Ne1Ck"
      short-id: "7548bc"
  - name: "🇸🇪_2"
    type: vless
    server: "meow-warsaw.nethcloud.top"
    port: 443
    uuid: "a34b5e88-cf0d-4c01-8199-2d1002d3c787"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.wikihow.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "HKpd1sbrhBds8SJSL0d22MAq_QyTR6EP6y5b5DYol3U"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_3"
    type: vless
    server: "217.217.245.252"
    port: 443
    uuid: "8ca5cbd3-ec16-4728-bedc-2bc0d82f0922"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "enterprisekitten.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_4"
    type: vless
    server: "217.217.245.253"
    port: 443
    uuid: "8ca5cbd3-ec16-4728-bedc-2bc0d82f0922"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "enterprisekitten.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_5"
    type: vless
    server: "smm.tunnelpoint.space"
    port: 443
    uuid: "06d44c57-8e1a-41f4-b9c4-65d35869e078"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "smm.tunnelpoint.space"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o"
      short-id: "fdda9806fe5d8584"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_6"
    type: vless
    server: "217.217.245.254"
    port: 443
    uuid: "8ca5cbd3-ec16-4728-bedc-2bc0d82f0922"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "enterprisekitten.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_7"
    type: vless
    server: "148.253.211.10"
    port: 443
    uuid: "60576147-90e7-4afc-9cf9-c7361a8c7fd8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.me"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "B3MWDjEWGQsObyH-9npa_PlkaoQDBqzwlwURFK1zlE8"
      short-id: "3e0527d94cc8d1"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_8"
    type: vless
    server: "v-de-node-03.bot-auth.com"
    port: 8443
    uuid: "b9b1e7c9-4160-49b4-85a4-2f096706509a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.oracle.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "dNfk0sOCzOlmE61B7ur7YzU2i08RqXIBcGVBA2Ne1Ck"
      short-id: "7548bc"
  - name: "🇸🇪_9"
    type: vless
    server: "217.217.245.251"
    port: 443
    uuid: "8ca5cbd3-ec16-4728-bedc-2bc0d82f0922"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "enterprisekitten.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_10"
    type: vless
    server: "150.241.72.5"
    port: 443
    uuid: "fc1b3bda-b226-452a-8c5c-b0e36a1f8f88"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_11"
    type: vless
    server: "217.217.245.250"
    port: 443
    uuid: "8ca5cbd3-ec16-4728-bedc-2bc0d82f0922"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "enterprisekitten.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_12"
    type: vless
    server: "185.229.221.83"
    port: 443
    uuid: "d1c624fc-d0b0-49c7-8afa-e15a5949bc17"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "st.onnstreaming.ru"
    client-fingerprint: "random"
    reality-opts:
      public-key: "1c7TsslPz_gsvzX4ENkEa36Pp3gm-M3SRLhvqtGaAz4"
      short-id: "e8e019c424ccb765"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_13"
    type: vless
    server: "st.onnstreaming.ru"
    port: 443
    uuid: "d1c624fc-d0b0-49c7-8afa-e15a5949bc17"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "st.onnstreaming.ru"
    client-fingerprint: "random"
    reality-opts:
      public-key: "1c7TsslPz_gsvzX4ENkEa36Pp3gm-M3SRLhvqtGaAz4"
      short-id: "e8e019c424ccb765"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"
      - "🇸🇪_11"
      - "🇸🇪_12"
      - "🇸🇪_13"


rules:
  - MATCH,PROXY
