name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇪_1"
    type: vless
    server: "148.253.211.10"
    port: 443
    uuid: "60576147-90e7-4afc-9cf9-c7361a8c7fd8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.me"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "B3MWDjEWGQsObyH-9npa_PlkaoQDBqzwlwURFK1zlE8"
      short-id: "3e0527d94cc8d1"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_2"
    type: vless
    server: "217.217.245.252"
    port: 443
    uuid: "8ca5cbd3-ec16-4728-bedc-2bc0d82f0922"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "enterprisekitten.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_3"
    type: vless
    server: "85.137.170.110"
    port: 443
    uuid: "06d44c57-8e1a-41f4-b9c4-65d35869e078"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "smm.tunnelpoint.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o"
      short-id: "fdda9806fe5d8584"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_4"
    type: vless
    server: "2.26.79.49"
    port: 443
    uuid: "18f71148-a3c7-40c7-b02a-be04da72efe3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pro-se.emrata.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AAZjVvbC7AwPKot_1ygO5VMpN7XYifCA7lG0RNR5sEk"
      short-id: ""
  - name: "🇸🇪_5"
    type: vless
    server: "31.207.7.159"
    port: 443
    uuid: "6eff5ebe-18bc-40fa-b9b1-f37648214309"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d3-se1.cloud-cdn.xyz"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "zWDvtTWK-cWWwHDMHMXcOpQy4k3EKp7yw-5e0wTZAUM"
      short-id: "5efa80b939612291"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_6"
    type: vless
    server: "217.217.245.253"
    port: 443
    uuid: "8ca5cbd3-ec16-4728-bedc-2bc0d82f0922"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "enterprisekitten.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_7"
    type: vless
    server: "150.241.79.143"
    port: 8443
    uuid: "b9b1e7c9-4160-49b4-85a4-2f096706509a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.oracle.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "dNfk0sOCzOlmE61B7ur7YzU2i08RqXIBcGVBA2Ne1Ck"
      short-id: "7548bc"
  - name: "🇸🇪_8"
    type: vless
    server: "pro-se.emrata.top"
    port: 443
    uuid: "2e4101cd-40b4-4d1a-8df6-cc949c136e5a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pro-se.emrata.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AAZjVvbC7AwPKot_1ygO5VMpN7XYifCA7lG0RNR5sEk"
      short-id: ""
  - name: "🇸🇪_9"
    type: vless
    server: "217.217.245.251"
    port: 443
    uuid: "8ca5cbd3-ec16-4728-bedc-2bc0d82f0922"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "enterprisekitten.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_10"
    type: vless
    server: "144.31.230.213"
    port: 443
    uuid: "4cbefb4d-328c-411d-bf76-780df1082df8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.wikihow.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HKpd1sbrhBds8SJSL0d22MAq_QyTR6EP6y5b5DYol3U"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_11"
    type: vless
    server: "185.189.44.201"
    port: 40443
    uuid: "ed2c5f6c-8383-4f7a-a231-c28916489f76"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tv.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "-cxFcuI9vCkNZvlwGFms4bENl_cZbOz2pUMOVCKB4j0"
      short-id: "e6bbe5cbfd3a1c9f"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_12"
    type: vless
    server: "150.241.72.5"
    port: 443
    uuid: "fc1b3bda-b226-452a-8c5c-b0e36a1f8f88"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_13"
    type: vless
    server: "89.22.224.146"
    port: 43788
    uuid: "49a6eeaf-7dbf-4aa5-ba21-b36cd47e724e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
  - name: "🇸🇪_14"
    type: vless
    server: "62.60.231.42"
    port: 2053
    uuid: "f7e0e597-636e-4550-9f54-6ab1c0e8cf49"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Xx3r5KsSKa1I8O3avmwMbgXOWj_-MqiqzTO_7BzBxyU"
      short-id: "58c5b3ee013bdc8f"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_15"
    type: vless
    server: "109.120.155.155"
    port: 444
    uuid: "c325206e-0f0c-4472-9d76-43e9b9b2ef63"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bapj1qapjk4.0sds0li1bwcz0i76it0gjxv1.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "bapj1qapjk4.0sds0li1bwcz0i76it0gjxv1.workers.dev"
  - name: "🇸🇪_16"
    type: vless
    server: "2.26.79.73"
    port: 443
    uuid: "18f71148-a3c7-40c7-b02a-be04da72efe3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pro-se.emrata.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AAZjVvbC7AwPKot_1ygO5VMpN7XYifCA7lG0RNR5sEk"
      short-id: ""
  - name: "🇸🇪_17"
    type: vless
    server: "109.120.155.155"
    port: 444
    uuid: "99ab6748-3d57-4562-9451-843c15960b9b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇸🇪_18"
    type: vless
    server: "31.77.111.11"
    port: 43439
    uuid: "428e923f-e608-412b-9e51-3b09ffab551f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.higames.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "39ad36226f3abec8"
    network: grpc
    grpc-opts:
      grpc-service-name: "streaming"
  - name: "🇸🇪_19"
    type: vless
    server: "31.207.7.48"
    port: 2096
    uuid: "2181d0c8-448a-4f75-b848-1718029baef9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-Dg4mGAAM5Lwe9ri7Bx5WlYdPBsyYJy-Pai2Z0FGlyc"
      short-id: "afee962d"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc2"
  - name: "🇸🇪_20"
    type: vless
    server: "st.onnstreaming.ru"
    port: 443
    uuid: "d1c624fc-d0b0-49c7-8afa-e15a5949bc17"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "st.onnstreaming.ru"
    client-fingerprint: "random"
    reality-opts:
      public-key: "1c7TsslPz_gsvzX4ENkEa36Pp3gm-M3SRLhvqtGaAz4"
      short-id: "e8e019c424ccb765"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_21"
    type: vless
    server: "185.229.221.83"
    port: 443
    uuid: "d1c624fc-d0b0-49c7-8afa-e15a5949bc17"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "st.onnstreaming.ru"
    client-fingerprint: "random"
    reality-opts:
      public-key: "1c7TsslPz_gsvzX4ENkEa36Pp3gm-M3SRLhvqtGaAz4"
      short-id: "e8e019c424ccb765"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_22"
    type: vless
    server: "smm.tunnelpoint.space"
    port: 443
    uuid: "06d44c57-8e1a-41f4-b9c4-65d35869e078"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "smm.tunnelpoint.space"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o"
      short-id: "fdda9806fe5d8584"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_23"
    type: vless
    server: "217.217.245.254"
    port: 443
    uuid: "8ca5cbd3-ec16-4728-bedc-2bc0d82f0922"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "enterprisekitten.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_24"
    type: vless
    server: "132.243.231.185"
    port: 443
    uuid: "b55a6115-07f5-4464-85b5-7059ce4701f3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "se.cloud-s3.xyz"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "b9f9fJEJm6RnFdH5wVMKQt4gqWngKi1wBApt-b1Q-h8"
      short-id: "7a3f9e2b1c8d4f6a"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_25"
    type: vless
    server: "213.176.112.136"
    port: 5222
    uuid: "8d955d71-ed5d-4f4c-ae68-42d120f06861"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
  - name: "🇸🇪_26"
    type: vless
    server: "217.217.245.250"
    port: 443
    uuid: "8ca5cbd3-ec16-4728-bedc-2bc0d82f0922"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "enterprisekitten.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_27"
    type: vless
    server: "95.85.246.19"
    port: 443
    uuid: "a34b5e88-cf0d-4c01-8199-2d1002d3c787"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.wikihow.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HKpd1sbrhBds8SJSL0d22MAq_QyTR6EP6y5b5DYol3U"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_28"
    type: vless
    server: "89.22.224.146"
    port: 43788
    uuid: "acc10ba5-a222-44b3-8a1a-4f247ffc6466"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
  - name: "🇸🇪_29"
    type: vless
    server: "2.26.79.22"
    port: 443
    uuid: "18f71148-a3c7-40c7-b02a-be04da72efe3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pro-se.emrata.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AAZjVvbC7AwPKot_1ygO5VMpN7XYifCA7lG0RNR5sEk"
      short-id: ""
  - name: "🇸🇪_30"
    type: vless
    server: "2.26.79.39"
    port: 443
    uuid: "18f71148-a3c7-40c7-b02a-be04da72efe3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pro-se.emrata.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AAZjVvbC7AwPKot_1ygO5VMpN7XYifCA7lG0RNR5sEk"
      short-id: ""
  - name: "🇸🇪_31"
    type: vless
    server: "85.137.170.110"
    port: 443
    uuid: "c04bf2df-2b7f-44da-a893-3792d3910fd8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "smm.tunnelpoint.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o"
      short-id: "fdda9806fe5d8584"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_32"
    type: vless
    server: "89.22.224.146"
    port: 43788
    uuid: "6fbd9bd1-ccd4-4e2f-a918-a0f871965763"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇸🇪_33"
    type: trojan
    server: "70.34.206.32"
    port: 443
    password: "Bw5Mz7QkVp"
    sni: "z-v2-077787.kailib.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_34"
    type: trojan
    server: "194.87.77.91"
    port: 443
    password: "1234567890"
    sni: "kfm-bn0.pages.dev"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_35"
    type: trojan
    server: "185.117.89.88"
    port: 9443
    password: "e72c6ea7e61f4dcea568aa569fb9b771"
    sni: "apple.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_36"
    type: trojan
    server: "45.91.171.116"
    port: 443
    password: "2ee85121-31de-4581-a492-eb00f606e392"
    sni: "sto.freeguard.org"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇪_37"
    type: trojan
    server: "65.20.113.246"
    port: 443
    password: "Bw5Mz7QkVp"
    sni: "z-v2-074389.kailib.com"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"
      - "🇸🇪_11"
      - "🇸🇪_12"
      - "🇸🇪_13"
      - "🇸🇪_14"
      - "🇸🇪_15"
      - "🇸🇪_16"
      - "🇸🇪_17"
      - "🇸🇪_18"
      - "🇸🇪_19"
      - "🇸🇪_20"
      - "🇸🇪_21"
      - "🇸🇪_22"
      - "🇸🇪_23"
      - "🇸🇪_24"
      - "🇸🇪_25"
      - "🇸🇪_26"
      - "🇸🇪_27"
      - "🇸🇪_28"
      - "🇸🇪_29"
      - "🇸🇪_30"
      - "🇸🇪_31"
      - "🇸🇪_32"
      - "🇸🇪_33"
      - "🇸🇪_34"
      - "🇸🇪_35"
      - "🇸🇪_36"
      - "🇸🇪_37"


rules:
  - MATCH,PROXY
