name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇹🇷_1"
    type: vless
    server: "185.39.204.155"
    port: 8443
    uuid: "7e8f7489-e65f-4be6-93ed-867a74ec6759"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇹🇷_2"
    type: vless
    server: "151.241.226.201"
    port: 2053
    uuid: "52b1aca9-a2ba-4249-9e9f-d488f89c1445"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "dUFJ3jZPMH9WvjtAnUc9wYhO_IX1czIi-CidF_HdFDA"
      short-id: "c267be657e1539ea"
  - name: "🇹🇷_3"
    type: vless
    server: "45.12.5.171"
    port: 443
    uuid: "b85b1e90-b5ed-0002-b433-bf9d2eca0e42"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ru9.aimodelhub.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jwT3lcIzJQMjzBKRNsmyRGrgaa1qNfE7pQF_nAKu0GA"
      short-id: "a73cf719b624"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_4"
    type: vless
    server: "46.229.251.93"
    port: 443
    uuid: "20df893e-dcf4-491d-8261-6dbb24f9566b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v-one.click"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "FVTSrw9PURI_lAPdckwoV4Or7Jh7CoYth_KS1mrG63A"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_5"
    type: vless
    server: "212.64.193.42"
    port: 443
    uuid: "0b596551-26c0-4d8d-8a4a-231b54418c28"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bg.cloudtechone.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_IBXb9NfhsnS21XbU9PIl73ExvrjXGXVLO0Za1ui5Fo"
      short-id: "f93c9d5127e622e4"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_6"
    type: vless
    server: "158.94.216.61"
    port: 57728
    uuid: "13efddd3-1a20-49f3-bbbe-f5b530398bb6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "_msWT9DtUixMc55dabeo7IqbWGikrSNz35GkoGllFBM"
      short-id: "85436cc1"
  - name: "🇹🇷_7"
    type: trojan
    server: "195.162.69.238"
    port: 9443
    password: "ac8ae2c29cd149eb85cae990572f0d59"
    sni: "apple.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇷_8"
    type: ss
    server: "38.60.255.97"
    port: 11201
    cipher: "chacha20-ietf-poly1305"
    password: "366aa1ba14af3f1a"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"

rules:
  - MATCH,PROXY
